/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class in_derros_jni_Utilities */

#ifndef _Included_in_derros_jni_Utilities
#define _Included_in_derros_jni_Utilities
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     in_derros_jni_Utilities
 * Method:    printMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_in_derros_jni_Utilities_printMethod
  (JNIEnv *, jobject);

/*
 * Class:     in_derros_jni_Utilities
 * Method:    trueFalse
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_in_derros_jni_Utilities_trueFalse
  (JNIEnv *, jobject);

/*
 * Class:     in_derros_jni_Utilities
 * Method:    power
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_in_derros_jni_Utilities_power
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
